### PR TITLE
Document additional editor features in tips and tricks

### PR DESCRIPTION
**Pull request by sinewavey**
With the creation of the [runtime example project](https://github.com/orgs/func-godot/repositories) I think it's worth briefly mentioning this process.

**This PR is still a "draft"**. Before I write the TrenchBroom section - or perhaps someone more familiar with TB can help me here - I'd also like some general feedback on wording, what else we could show or remove.

[Here is a live version of this branch](http://sine.fyi/func_godot_docs/FuncGodot%20Manual/FuncGodot%20Manual.html)

### CODE REVIEW

**Comment by RisingThumb** [comment]
> This PR is still a "draft". Before I write the TrenchBroom section - or perhaps someone more familiar with TB can help me here - I'd also like some general feedback on wording, what else we could show or remove. I'm happy to add this seperately after this is merged, but feel free to address it yourself if you'd like

For Trenchbroom, the process is similar on the Godot side with commandline args. What needs to be done is to go to `Run->Launch Engine`. You will get a page looking like this
image

You can then Configure engines to add an exe option
image
After configuring it, you go back to the Launch Engine options, and add the CLI parameters you'd want. Trenchbroom has some variables to help get the right path to the .map file . https://trenchbroom.github.io/manual/latest/#launching_game_engines.

Could you add a link to your github pages of the docs?

**Comment by RisingThumb** [comment]
Looking at the live version, I've got a handful of comments:
For the screenshot with code, I'd prefer an actual code block instead.
The final image produces a horizontal scrollbar on a screen of ~1920x1080. We should do something in CSS to stop large images from producing horizontal scrollbars.

**Comment by sinewavey** [comment]
Funny, I debated mentally to use a code block vs a screenshot, and with the other docs using a screenshot, I went with that.

The final image can be easily cropped or excluded, to be honest. 

Will update in a bit

**Comment by RisingThumb** [comment]
> Funny, I debated mentally to use a code block vs a screenshot, and with the other docs using a screenshot, I went with that.

Yeah, the worldspawn docs use `<pre>` tags for it. I think the only instance of screenshotted code is in the ForgeGameData page(though there might be other instances too) though that's not code intended to be used by others, but what the addon is doing behind the scenes

**Pull request closed without merging**
